#include "main.h"
uchar anniujishu_i=0,anniu_zhuangtai_flag[6]={0,0,0,0,0,0},anniuzhuangtai[6][50],mimawei2=0;
uchar mimawei=0;
extern uchar jiguankaiqi_flag;
extern uint ShouDaoFanHui_flag,ceshi;
void anniu_init(void)
{
	for(anniujishu_i=0;anniujishu_i<50;anniujishu_i++)	
	{
		anniuzhuangtai[0][anniujishu_i]=0;
		anniuzhuangtai[1][anniujishu_i]=0;
		anniuzhuangtai[2][anniujishu_i]=0;
		anniuzhuangtai[3][anniujishu_i]=0;
		anniuzhuangtai[4][anniujishu_i]=0;
		anniuzhuangtai[5][anniujishu_i]=0;
	}
}
void anniupanduan(void)
{
	for(anniujishu_i=0;anniujishu_i<6;anniujishu_i++)
	{
		anniu_zhuangtai_flag[anniujishu_i]=anniu_zhuangtai_flag[anniujishu_i]-anniuzhuangtai[anniujishu_i][49];
	}
	for(anniujishu_i=49;anniujishu_i>0;anniujishu_i--)
	{		
		anniuzhuangtai[0][anniujishu_i]=anniuzhuangtai[0][anniujishu_i-1];
		anniuzhuangtai[1][anniujishu_i]=anniuzhuangtai[1][anniujishu_i-1];
		anniuzhuangtai[2][anniujishu_i]=anniuzhuangtai[2][anniujishu_i-1];
		anniuzhuangtai[3][anniujishu_i]=anniuzhuangtai[3][anniujishu_i-1];
		anniuzhuangtai[4][anniujishu_i]=anniuzhuangtai[4][anniujishu_i-1];
		anniuzhuangtai[5][anniujishu_i]=anniuzhuangtai[5][anniujishu_i-1];		
	}	 
	if(SHURU_1==1)
	{
		anniuzhuangtai[0][0]=1;
	}else{
	  	anniuzhuangtai[0][0]=0;
	}
	if(SHURU_2==1)
	{
		anniuzhuangtai[1][0]=1;
	}else{
	  	anniuzhuangtai[1][0]=0;
	}
	if(SHURU_3==1)
	{
		anniuzhuangtai[2][0]=1;
	}else{
	  	anniuzhuangtai[2][0]=0;
	}
	if(SHURU_4==1)
	{
		anniuzhuangtai[3][0]=1;
	}else{
	  	anniuzhuangtai[3][0]=0;
	}
	if(SHURU_5==1)
	{
		anniuzhuangtai[4][0]=1;
	}else{
	  	anniuzhuangtai[4][0]=0;
	}
	if(SHURU_6==1)
	{
		anniuzhuangtai[5][0]=1;
	}else{
	  	anniuzhuangtai[5][0]=0;
	}
   	for(anniujishu_i=0;anniujishu_i<6;anniujishu_i++)
	{
		anniu_zhuangtai_flag[anniujishu_i]=anniu_zhuangtai_flag[anniujishu_i]+anniuzhuangtai[anniujishu_i][0];
	}
}
void anniusaomiao(void)
{
	if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]<25)&&(anniu_zhuangtai_flag[2]<25)&&(anniu_zhuangtai_flag[3]<25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
	{
		if(mimawei2==0)
		{
			mimawei2=1;
		}
	}else if(anniu_zhuangtai_flag[0]<25){
		if(mimawei2>0)	
			mimawei2=0;
	}
	if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]<25)&&(anniu_zhuangtai_flag[3]<25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
	{
		if(mimawei2==1)
		{
			mimawei2=2;
		}	
	}else if((anniu_zhuangtai_flag[1]<25)&&(mimawei2>1)){ 
		if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]<25)&&(anniu_zhuangtai_flag[2]<25)&&(anniu_zhuangtai_flag[3]<25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
			mimawei2=1;
		if(mimawei2>2)
		{	
			mimawei2=0;
		}
	}
	if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]>25)&&(anniu_zhuangtai_flag[3]<25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
	{
		if(mimawei2==2)
		{
			mimawei2=3;
		}	
	}else if((anniu_zhuangtai_flag[2]<25)&&(mimawei2>2)){ 
		if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]<25)&&(anniu_zhuangtai_flag[3]<25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
			mimawei2=2;
		if(mimawei2>3)
		{	
			mimawei2=0;
		}
	}
	if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]>25)&&(anniu_zhuangtai_flag[3]>25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
	{
		if(mimawei2==3)
		{
			mimawei2=4;
		}	
	}else if((anniu_zhuangtai_flag[3]<25)&&(mimawei2>3)){ 
		if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]>25)&&(anniu_zhuangtai_flag[3]<25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
			mimawei2=3;
		if(mimawei2>4)
		{	
			mimawei2=0;
		}
	}
	if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]>25)&&(anniu_zhuangtai_flag[3]>25)&&(anniu_zhuangtai_flag[4]>25)&&(anniu_zhuangtai_flag[5]<25))
	{
		if(mimawei2==4)
		{
			mimawei2=5;
		}	
	}else if((anniu_zhuangtai_flag[4]<25)&&(mimawei2>4)){ 
		if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]>25)&&(anniu_zhuangtai_flag[3]>25)&&(anniu_zhuangtai_flag[4]<25)&&(anniu_zhuangtai_flag[5]<25))
			mimawei2=4;
		if(mimawei2>5)
		{	
			mimawei2=0;
		}
	}
	if((anniu_zhuangtai_flag[0]>25)&&(anniu_zhuangtai_flag[1]>25)&&(anniu_zhuangtai_flag[2]>25)&&(anniu_zhuangtai_flag[3]>25)&&(anniu_zhuangtai_flag[4]>25)&&(anniu_zhuangtai_flag[5]>25))
	{
		if(mimawei2==5)
		{
			mimawei2=6;
			jiguankaiqi_flag=1;
			mimawei2=6;
			ShouDaoFanHui_flag=1;
		}	
	}
}