#include "main.h"

uchar Key1_flag=0,Key2_flag=0,Key3_flag=0,Key4_flag=0,Key5_flag=0,Key6_flag=0,Key7_flag=0,Key8_flag=0,Key_WeiZhi=0;
uint Key1_tium=0,Key2_tium=0,Key3_tium=0,Key4_tium=0,Key5_tium=0,Key6_tium=0,Key7_tium=0,Key8_tium=0;

void ShunXu_PanDuan(void)
{
	switch(Key_WeiZhi)
	{
	 	case 0:
			if((Key1_flag==1)&&(Key2_flag==0)&&(Key3_flag==0)&&(Key4_flag==0)&&(Key5_flag==0)&&(Key6_flag==0)&&(Key7_flag==0)&&(Key8_flag==0))
			{
				Key1_flag=2;
				Key_WeiZhi=1;
			}
		break;
	 	case 1:
			if(Key2_flag==1)
			{
				Key2_flag=2;
				Key_WeiZhi=2;
			}
			if(changfang==1)
			{
				if(Key1_flag==0)
				{
					Key_WeiZhi=0;
				}	
			}
			if((Key1_flag==1)||(Key3_flag==1)||(Key4_flag==1)||(Key5_flag==1)||(Key6_flag==1)||(Key7_flag==1)||(Key8_flag==1))
			{
				Key_WeiZhi=0;	
			}
		break;
	 	case 2:
			if(Key3_flag==1)
			{
				Key3_flag=2;
				Key_WeiZhi=3;
			}
			if(changfang==1)
			{
				if(Key1_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key2_flag==0)
				{
					Key_WeiZhi=1;
				}	
			}
			if((Key1_flag==1)||(Key2_flag==1)||(Key4_flag==1)||(Key5_flag==1)||(Key6_flag==1)||(Key7_flag==1)||(Key8_flag==1))
			{
				Key_WeiZhi=0;	
			}
		break;
	 	case 3:
			if(Key4_flag==1)
			{
				Key4_flag=2;
				Key_WeiZhi=4;
				deng=1;
				jidianqi=1;
				yingxiaokongzhi(2,1);
			}
			if(changfang==1)
			{
				if(Key1_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key2_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key3_flag==0)
				{
					Key_WeiZhi=2;
				}	
			}
			if((Key1_flag==1)||(Key2_flag==1)||(Key3_flag==1)||(Key5_flag==1)||(Key6_flag==1)||(Key7_flag==1)||(Key8_flag==1))
			{
				Key_WeiZhi=0;	
			}
		break;
	 	case 4:
			if(Key5_flag==1)
			{
				Key5_flag=2;
				Key_WeiZhi=5;
			}
			if(changfang==1)
			{
				if(Key1_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key2_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key3_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key4_flag==0)
				{
					Key_WeiZhi=3;
				}	
			}
			if((Key1_flag==1)||(Key2_flag==1)||(Key3_flag==1)||(Key4_flag==1)||(Key6_flag==1)||(Key7_flag==1)||(Key8_flag==1))
			{
				Key_WeiZhi=0;	
			}
		break;
	 	case 5:
			if(Key6_flag==1)
			{
				Key6_flag=2;
				Key_WeiZhi=6;
			}
			if(changfang==1)
			{
				if(Key1_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key2_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key3_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key4_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key5_flag==0)
				{
					Key_WeiZhi=4;
				}	
			}
			if((Key1_flag==1)||(Key2_flag==1)||(Key3_flag==1)||(Key4_flag==1)||(Key5_flag==1)||(Key7_flag==1)||(Key8_flag==1))
			{
				Key_WeiZhi=0;	
			}
		break;
	 	case 6:
			if(Key7_flag==1)
			{
				Key7_flag=2;
				Key_WeiZhi=7;
			}
			if(changfang==1)
			{
				if(Key1_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key2_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key3_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key4_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key5_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key6_flag==0)
				{
					Key_WeiZhi=5;
				}	
			}
			if((Key1_flag==1)||(Key2_flag==1)||(Key3_flag==1)||(Key4_flag==1)||(Key5_flag==1)||(Key6_flag==1)||(Key8_flag==1))
			{
				Key_WeiZhi=0;	
			}
		break;
	 	case 7:
			if(Key8_flag==1)
			{
				Key8_flag=2;
				Key_WeiZhi=8;
			}
			if(changfang==1)
			{
				if(Key1_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key2_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key3_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key4_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key5_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key6_flag==0)
				{
					Key_WeiZhi=0;
				}
				if(Key7_flag==0)
				{
					Key_WeiZhi=6;
				}	
			}
			if((Key1_flag==1)||(Key2_flag==1)||(Key3_flag==1)||(Key4_flag==1)||(Key5_flag==1)||(Key6_flag==1)||(Key7_flag==1))
			{
				Key_WeiZhi=0;	
			}
		break;
	}
}

void ShunXu_Tium(void)
{
	if(Key1_flag==0)
	{
		if(Key1==1)
		{
		    Key1_tium++; 
			if(Key1_tium>200) 
			{
				Key1_flag=1;
				Key1_tium=0;    
			}
		}else{
			Key1_tium=0;
		}
	}else{
		if(Key1==0)
		{
		    Key1_tium++;
			if(Key1_tium>200)
			{
				Key1_flag=0; 	
			}
		}else{
			Key1_tium=0;
		}
	} 

	if(Key2_flag==0)
	{
		if(Key2==1)
		{
		    Key2_tium++; 
			if(Key2_tium>200) 
			{
				Key2_flag=1;
				Key2_tium=0;    
			}
		}else{
			Key2_tium=0;
		}
	}else{
		if(Key2==0)
		{
		    Key2_tium++;
			if(Key2_tium>200)
			{
				Key2_flag=0; 	
			}
		}else{
			Key2_tium=0;
		}
	} 
	if(Key3_flag==0)
	{
		if(Key3==1)
		{
		    Key3_tium++; 
			if(Key3_tium>200) 
			{
				if(Key3_flag!=2)
					Key3_flag=1;
				Key3_tium=0;    
			}
		}else{
			Key3_tium=0;
		}
	}else{
		if(Key3==0)
		{
		    Key3_tium++;  
			if(Key3_tium>200)
			{
				Key3_flag=0; 	
			}
		}else{
			Key3_tium=0;
		}
	}
	if(Key4_flag==0)
	{
		if(Key4==1)
		{
		    Key4_tium++; 
			if(Key4_tium>200) 
			{
				if(Key4_flag!=2)
					Key4_flag=1;
				Key4_tium=0;    
			}
		}else{
			Key4_tium=0;
		}
	}else{
		if(Key4==0)
		{
		    Key4_tium++;  
			if(Key4_tium>200)
			{
				Key4_flag=0; 	
			}
		}else{
			Key4_tium=0;
		}
	}
	/*if(Key5_flag==0)
	{
		if(Key5==1)
		{
		    Key5_tium++; 
			if(Key5_tium>200) 
			{
				if(Key5_flag!=2)
					Key5_flag=1;
				Key5_tium=0;    
			}
		}else{
			Key5_tium=0;
		}
	}else{
		if(Key5==0)
		{
		    Key5_tium++;  
			if(Key5_tium>200)
			{
				Key5_flag=0; 	
			}
		}else{
			Key5_tium=0;
		}
	}
	if(Key6_flag==0)
	{
		if(Key6==1)
		{
		    Key6_tium++; 
			if(Key6_tium>200) 
			{
				if(Key6_flag!=2)
					Key6_flag=1;
				Key6_tium=0;    
			}
		}else{
			Key6_tium=0;
		}
	}else{
		if(Key6==0)
		{
		    Key6_tium++;  
			if(Key6_tium>200)
			{
				Key6_flag=0; 	
			}
		}else{
			Key6_tium=0;
		}
	}
	if(Key7_flag==0)
	{
		if(Key7==1)
		{
		    Key7_tium++; 
			if(Key7_tium>200) 
			{
				if(Key7_flag!=2)
					Key7_flag=1;
				Key7_tium=0;    
			}
		}else{
			Key7_tium=0;
		}
	}else{
		if(Key7==0)
		{
		    Key7_tium++;  
			if(Key7_tium>200)
			{
				Key7_flag=0; 	
			}
		}else{
			Key7_tium=0;
		}
	}
	if(Key8_flag==0)
	{
		if(Key8==1)
		{
		    Key8_tium++; 
			if(Key8_tium>200) 
			{
				if(Key8_flag!=2)
					Key8_flag=1;
				Key8_tium=0;    
			}
		}else{
			Key8_tium=0;
		}
	}else{
		if(Key8==0)
		{
		    Key8_tium++;  
			if(Key8_tium>200)
			{
				Key8_flag=0; 	
			}
		}else{
			Key8_tium=0;
		}
	}*/
}