#include "main.h"
uchar zhongdianshu=0,xiongmeng[7]={0,0,0,0,0,0,0},guizha[7]={0,0,0,0,0,0,0},jianjue[7]={0,0,0,0,0,0,0},fuwei_i=0;
extern uchar anniu_zhuangtai[42],dengzhuangtai[42];
void tianfukongzhi(void)
{
/*********************************************************
						Ð×ÃÍ
**********************************************************/
	if(xiongmeng[0]==0)
	{
	 	if(anniu_zhuangtai[0]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=1;	
				xiongmeng[1]=1;
				dengzhuangtai[0]=1;
				zhongdianshu++;
			}	
		}
		if(anniu_zhuangtai[1]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=1;	
				xiongmeng[1]=2;	
				dengzhuangtai[1]=1;
				zhongdianshu++;
			}
		}
	}else if(xiongmeng[0]==1)
	{
		if(anniu_zhuangtai[0]==1)
		{
			if(xiongmeng[1]==1)
			{
				xiongmeng[0]=0;	
				xiongmeng[1]=0;
				dengzhuangtai[0]=0;
				zhongdianshu--;	
			}else if(xiongmeng[1]==2)
			{	
				xiongmeng[1]=1;
				dengzhuangtai[0]=1;
				dengzhuangtai[1]=0;
			}	
		}
		if(anniu_zhuangtai[1]==1)
		{
			if(xiongmeng[1]==2)
			{
				xiongmeng[0]=0;	
				xiongmeng[1]=0;
				zhongdianshu--;	
				dengzhuangtai[1]=0;
			}else if(xiongmeng[1]==1)
			{	
				xiongmeng[1]=2;
				dengzhuangtai[1]=1;
				dengzhuangtai[0]=0;
			}	
		}
		if(anniu_zhuangtai[2]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=2;	
				xiongmeng[2]=1;
				dengzhuangtai[2]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[3]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=2;	
				xiongmeng[2]=2;	
				dengzhuangtai[3]=1;
				zhongdianshu++;
			}
		}
	}else if(xiongmeng[0]==2)
	{
		if(anniu_zhuangtai[2]==1)
		{
			if(xiongmeng[2]==1)
			{
				xiongmeng[0]=1;	
				xiongmeng[2]=0;
				dengzhuangtai[2]=0;
				zhongdianshu--;	
			}else if(xiongmeng[2]==2)
			{	
				xiongmeng[2]=1;
				dengzhuangtai[2]=1;
				dengzhuangtai[3]=0;
			}	
		}
		if(anniu_zhuangtai[3]==1)
		{
			if(xiongmeng[2]==2)
			{
				xiongmeng[0]=1;	
				xiongmeng[2]=0;
				zhongdianshu--;	
				dengzhuangtai[3]=0;
			}else if(xiongmeng[2]==1)
			{	
				xiongmeng[2]=2;
				dengzhuangtai[3]=1;
				dengzhuangtai[2]=0;
			}	
		}
		if(anniu_zhuangtai[4]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=3;	
				xiongmeng[3]=1;
				dengzhuangtai[4]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[39]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=3;	
				xiongmeng[3]=2;	
				dengzhuangtai[39]=1;
				zhongdianshu++;
			}
		}
	}else if(xiongmeng[0]==3)
	{
		if(anniu_zhuangtai[4]==1)
		{
			if(xiongmeng[3]==1)
			{
				xiongmeng[0]=2;	
				xiongmeng[3]=0;
				dengzhuangtai[4]=0;
				zhongdianshu--;	
			}else if(xiongmeng[3]==2)
			{	
				xiongmeng[3]=1;
				dengzhuangtai[4]=1;
				dengzhuangtai[39]=0;
			}	
		}
		if(anniu_zhuangtai[39]==1)
		{
			if(xiongmeng[3]==2)
			{
				xiongmeng[0]=2;	
				xiongmeng[3]=0;
				zhongdianshu--;	
				dengzhuangtai[39]=0;
			}else if(xiongmeng[3]==1)
			{	
				xiongmeng[3]=2;
				dengzhuangtai[39]=1;
				dengzhuangtai[4]=0;
			}	
		}
		if(anniu_zhuangtai[5]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=4;	
				xiongmeng[4]=1;
				dengzhuangtai[5]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[6]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=4;	
				xiongmeng[4]=2;	
				dengzhuangtai[6]=1;
				zhongdianshu++;
			}
		}
	}else if(xiongmeng[0]==4)
	{
		if(anniu_zhuangtai[5]==1)
		{
			if(xiongmeng[4]==1)
			{
				xiongmeng[0]=3;	
				xiongmeng[4]=0;
				dengzhuangtai[5]=0;
				zhongdianshu--;	
			}else if(xiongmeng[4]==2)
			{	
				xiongmeng[4]=1;
				dengzhuangtai[5]=1;
				dengzhuangtai[6]=0;
			}	
		}
		if(anniu_zhuangtai[6]==1)
		{
			if(xiongmeng[4]==2)
			{
				xiongmeng[0]=3;	
				xiongmeng[4]=0;
				zhongdianshu--;	
				dengzhuangtai[6]=0;
			}else if(xiongmeng[4]==1)
			{	
				xiongmeng[4]=2;
				dengzhuangtai[6]=1;
				dengzhuangtai[5]=0;
			}	
		}
		if(anniu_zhuangtai[7]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=5;	
				xiongmeng[5]=1;
				dengzhuangtai[7]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[8]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=5;	
				xiongmeng[5]=2;	
				dengzhuangtai[8]=1;
				zhongdianshu++;
			}
		}
	}else if(xiongmeng[0]==5)
	{
		if(anniu_zhuangtai[7]==1)
		{
			if(xiongmeng[5]==1)
			{
				xiongmeng[0]=4;	
				xiongmeng[5]=0;
				dengzhuangtai[7]=0;
				zhongdianshu--;	
			}else if(xiongmeng[5]==2)
			{	
				xiongmeng[5]=1;
				dengzhuangtai[7]=1;
				dengzhuangtai[8]=0;
			}	
		}
		if(anniu_zhuangtai[8]==1)
		{
			if(xiongmeng[5]==2)
			{
				xiongmeng[0]=4;	
				xiongmeng[5]=0;
				zhongdianshu--;	
				dengzhuangtai[8]=0;
			}else if(xiongmeng[5]==1)
			{	
				xiongmeng[5]=2;
				dengzhuangtai[8]=1;
				dengzhuangtai[7]=0;
			}	
		}
		if(anniu_zhuangtai[9]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=6;	
				xiongmeng[6]=1;
				dengzhuangtai[9]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[10]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=6;	
				xiongmeng[6]=2;	
				dengzhuangtai[10]=1;
				zhongdianshu++;
			}
		}
		if(anniu_zhuangtai[11]==1)
		{
			if(zhongdianshu<zong_max)
			{
				xiongmeng[0]=6;	
				xiongmeng[6]=3;	
				dengzhuangtai[11]=1;
				zhongdianshu++;
			}
		}
	}else if(xiongmeng[0]==6)
	{
		if(anniu_zhuangtai[9]==1)
		{
			if(xiongmeng[6]==1)
			{
				xiongmeng[0]=5;	
				xiongmeng[6]=0;
				dengzhuangtai[9]=0;
				zhongdianshu--;	
			}else if(xiongmeng[6]!=1)
			{	
				xiongmeng[6]=1;
				dengzhuangtai[9]=1;
				dengzhuangtai[10]=0;
				dengzhuangtai[11]=0;
			}	
		}
		if(anniu_zhuangtai[10]==1)
		{
			if(xiongmeng[6]==2)
			{
				xiongmeng[0]=5;	
				xiongmeng[6]=0;
				zhongdianshu--;	
				dengzhuangtai[10]=0;
			}else if(xiongmeng[6]!=2)
			{	
				xiongmeng[6]=2;
				dengzhuangtai[10]=1;
				dengzhuangtai[9]=0;
				dengzhuangtai[11]=0;
			}	
		}
		if(anniu_zhuangtai[11]==1)
		{
			if(xiongmeng[6]==3)
			{
				xiongmeng[0]=5;	
				xiongmeng[6]=0;
				zhongdianshu--;	
				dengzhuangtai[11]=0;
			}else if(xiongmeng[6]!=3)
			{	
				xiongmeng[6]=3;
				dengzhuangtai[11]=1;
				dengzhuangtai[9]=0;
				dengzhuangtai[10]=0;
			}	
		}
	}
/*********************************************************
						¹îÕ©
**********************************************************/	
	if(guizha[0]==0)
	{
	 	if(anniu_zhuangtai[12]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=1;	
				guizha[1]=1;
				dengzhuangtai[12]=1;
				zhongdianshu++;
			}	
		}
		if(anniu_zhuangtai[13]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=1;	
				guizha[1]=2;	
				dengzhuangtai[13]=1;
				zhongdianshu++;
			}
		}
	}else if(guizha[0]==1)
	{
		if(anniu_zhuangtai[12]==1)
		{
			if(guizha[1]==1)
			{
				guizha[0]=0;	
				guizha[1]=0;
				dengzhuangtai[12]=0;
				zhongdianshu--;	
			}else if(guizha[1]!=1)
			{	
				guizha[1]=1;
				dengzhuangtai[12]=1;
				dengzhuangtai[13]=0;
			}	
		}
		if(anniu_zhuangtai[13]==1)
		{
			if(guizha[1]==2)
			{
				guizha[0]=0;	
				guizha[1]=0;
				zhongdianshu--;	
				dengzhuangtai[13]=0;
			}else if(guizha[1]!=2)
			{	
				guizha[1]=2;
				dengzhuangtai[13]=1;
				dengzhuangtai[12]=0;
			}	
		}
		if(anniu_zhuangtai[14]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=2;	
				guizha[2]=1;
				dengzhuangtai[14]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[15]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=2;	
				guizha[2]=2;	
				dengzhuangtai[15]=1;
				zhongdianshu++;
			}
		}
		if(anniu_zhuangtai[16]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=2;	
				guizha[2]=3;	
				dengzhuangtai[16]=1;
				zhongdianshu++;
			}
		}
	}else if(guizha[0]==2)
	{
		if(anniu_zhuangtai[14]==1)
		{
			if(guizha[2]==1)
			{
				guizha[0]=1;	
				guizha[2]=0;
				dengzhuangtai[14]=0;
				zhongdianshu--;	
			}else if(guizha[2]!=1)
			{	
				guizha[2]=1;
				dengzhuangtai[14]=1;
				dengzhuangtai[15]=0;
				dengzhuangtai[16]=0;
			}	
		}
		if(anniu_zhuangtai[15]==1)
		{
			if(guizha[2]==2)
			{
				guizha[0]=1;	
				guizha[2]=0;
				dengzhuangtai[15]=0;
				zhongdianshu--;	
			}else if(guizha[2]!=2)
			{	
				guizha[2]=2;
				dengzhuangtai[15]=1;
				dengzhuangtai[14]=0;
				dengzhuangtai[16]=0;
			}	
		}
		if(anniu_zhuangtai[16]==1)
		{
			if(guizha[2]==3)
			{
				guizha[0]=1;	
				guizha[2]=0;
				dengzhuangtai[16]=0;
				zhongdianshu--;	
			}else if(guizha[2]!=3)
			{	
				guizha[2]=3;
				dengzhuangtai[16]=1;
				dengzhuangtai[15]=0;
				dengzhuangtai[14]=0;
			}	
		}
		if(anniu_zhuangtai[17]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=3;	
				guizha[3]=1;
				dengzhuangtai[17]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[18]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=3;	
				guizha[3]=2;	
				dengzhuangtai[18]=1;
				zhongdianshu++;
			}
		}
	}else if(guizha[0]==3)
	{
		if(anniu_zhuangtai[17]==1)
		{
			if(guizha[3]==1)
			{
				guizha[0]=2;	
				guizha[3]=0;
				dengzhuangtai[17]=0;
				zhongdianshu--;	
			}else if(guizha[3]!=1)
			{	
				guizha[3]=1;
				dengzhuangtai[17]=1;
				dengzhuangtai[18]=0;
			}	
		}
		if(anniu_zhuangtai[18]==1)
		{
			if(guizha[3]==2)
			{
				guizha[0]=2;	
				guizha[3]=0;
				dengzhuangtai[18]=0;
				zhongdianshu--;	
			}else if(guizha[3]!=2)
			{	
				guizha[3]=2;
				dengzhuangtai[18]=1;
				dengzhuangtai[17]=0;
			}	
		}
		if(anniu_zhuangtai[19]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=4;	
				guizha[4]=1;
				dengzhuangtai[19]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[20]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=4;	
				guizha[4]=2;	
				dengzhuangtai[20]=1;
				zhongdianshu++;
			}
		}
	}else if(guizha[0]==4)
	{
		if(anniu_zhuangtai[19]==1)
		{
			if(guizha[4]==1)
			{
				guizha[0]=3;	
				guizha[4]=0;
				dengzhuangtai[19]=0;
				zhongdianshu--;	
			}else if(guizha[4]!=1)
			{	
				guizha[4]=1;
				dengzhuangtai[19]=1;
				dengzhuangtai[20]=0;
			}	
		}
		if(anniu_zhuangtai[20]==1)
		{
			if(guizha[4]==2)
			{
				guizha[0]=3;	
				guizha[4]=0;
				dengzhuangtai[20]=0;
				zhongdianshu--;	
			}else if(guizha[4]!=2)
			{	
				guizha[4]=2;
				dengzhuangtai[20]=1;
				dengzhuangtai[19]=0;
			}	
		}
		if(anniu_zhuangtai[21]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=5;	
				guizha[5]=1;
				dengzhuangtai[21]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[22]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=5;	
				guizha[5]=2;	
				dengzhuangtai[22]=1;
				zhongdianshu++;
			}
		}
	}else if(guizha[0]==5)
	{
		if(anniu_zhuangtai[21]==1)
		{
			if(guizha[5]==1)
			{
				guizha[0]=4;	
				guizha[5]=0;
				dengzhuangtai[21]=0;
				zhongdianshu--;	
			}else if(guizha[5]!=1)
			{	
				guizha[5]=1;
				dengzhuangtai[21]=1;
				dengzhuangtai[22]=0;
			}	
		}
		if(anniu_zhuangtai[22]==1)
		{
			if(guizha[5]==2)
			{
				guizha[0]=4;	
				guizha[5]=0;
				dengzhuangtai[22]=0;
				zhongdianshu--;	
			}else if(guizha[5]!=2)
			{	
				guizha[5]=2;
				dengzhuangtai[22]=1;
				dengzhuangtai[21]=0;
			}	
		}
		if(anniu_zhuangtai[23]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=6;	
				guizha[6]=1;
				dengzhuangtai[23]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[24]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=6;	
				guizha[6]=2;	
				dengzhuangtai[24]=1;
				zhongdianshu++;
			}
		}
		if(anniu_zhuangtai[25]==1)
		{
			if(zhongdianshu<zong_max)
			{
				guizha[0]=6;	
				guizha[6]=3;	
				dengzhuangtai[25]=1;
				zhongdianshu++;
			}
		}
	}else if(guizha[0]==6)
	{
		if(anniu_zhuangtai[23]==1)
		{
			if(guizha[6]==1)
			{
				guizha[0]=5;	
				guizha[6]=0;
				dengzhuangtai[23]=0;
				zhongdianshu--;	
			}else if(guizha[6]!=1)
			{	
				guizha[6]=1;
				dengzhuangtai[23]=1;
				dengzhuangtai[24]=0;
				dengzhuangtai[25]=0;
			}	
		}
		if(anniu_zhuangtai[24]==1)
		{
			if(guizha[6]==2)
			{
				guizha[0]=5;	
				guizha[6]=0;
				dengzhuangtai[24]=0;
				zhongdianshu--;	
			}else if(guizha[6]!=2)
			{	
				guizha[6]=2;
				dengzhuangtai[24]=1;
				dengzhuangtai[23]=0;
				dengzhuangtai[25]=0;
			}	
		}
		if(anniu_zhuangtai[25]==1)
		{
			if(guizha[6]==3)
			{
				guizha[0]=5;	
				guizha[6]=0;
				dengzhuangtai[25]=0;
				zhongdianshu--;	
			}else if(guizha[6]!=3)
			{	
				guizha[6]=3;
				dengzhuangtai[25]=1;
				dengzhuangtai[23]=0;
				dengzhuangtai[24]=0;
			}	
		}
	}
/*********************************************************
						¼á¾ö
**********************************************************/
	if(jianjue[0]==0)
	{
	 	if(anniu_zhuangtai[26]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=1;	
				jianjue[1]=1;
				dengzhuangtai[26]=1;
				zhongdianshu++;
			}	
		}
		if(anniu_zhuangtai[27]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=1;	
				jianjue[1]=2;	
				dengzhuangtai[27]=1;
				zhongdianshu++;
			}
		}
	}else if(jianjue[0]==1)
	{
		if(anniu_zhuangtai[26]==1)
		{
			if(jianjue[1]==1)
			{
				jianjue[0]=0;	
				jianjue[1]=0;
				dengzhuangtai[26]=0;
				zhongdianshu--;	
			}else if(jianjue[1]==2)
			{	
				jianjue[1]=1;
				dengzhuangtai[26]=1;
				dengzhuangtai[27]=0;
			}	
		}
		if(anniu_zhuangtai[27]==1)
		{
			if(jianjue[1]==2)
			{
				jianjue[0]=0;	
				jianjue[1]=0;
				zhongdianshu--;	
				dengzhuangtai[27]=0;
			}else if(jianjue[1]==1)
			{	
				jianjue[1]=2;
				dengzhuangtai[27]=1;
				dengzhuangtai[26]=0;
			}	
		}
		if(anniu_zhuangtai[28]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=2;	
				jianjue[2]=1;
				dengzhuangtai[28]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[29]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=2;	
				jianjue[2]=2;	
				dengzhuangtai[29]=1;
				zhongdianshu++;
			}
		}
	}else if(jianjue[0]==2)
	{
		if(anniu_zhuangtai[28]==1)
		{
			if(jianjue[2]==1)
			{
				jianjue[0]=1;	
				jianjue[2]=0;
				dengzhuangtai[28]=0;
				zhongdianshu--;	
			}else if(jianjue[2]==2)
			{	
				jianjue[2]=1;
				dengzhuangtai[28]=1;
				dengzhuangtai[29]=0;
			}	
		}
		if(anniu_zhuangtai[29]==1)
		{
			if(jianjue[2]==2)
			{
				jianjue[0]=1;	
				jianjue[2]=0;
				zhongdianshu--;	
				dengzhuangtai[29]=0;
			}else if(jianjue[2]==1)
			{	
				jianjue[2]=2;
				dengzhuangtai[29]=1;
				dengzhuangtai[28]=0;
			}	
		}
		if(anniu_zhuangtai[30]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=3;	
				jianjue[3]=1;
				dengzhuangtai[30]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[31]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=3;	
				jianjue[3]=2;	
				dengzhuangtai[31]=1;
				zhongdianshu++;
			}
		}
	}else if(jianjue[0]==3)
	{
		if(anniu_zhuangtai[30]==1)
		{
			if(jianjue[3]==1)
			{
				jianjue[0]=2;	
				jianjue[3]=0;
				dengzhuangtai[30]=0;
				zhongdianshu--;	
			}else if(jianjue[3]==2)
			{	
				jianjue[3]=1;
				dengzhuangtai[30]=1;
				dengzhuangtai[31]=0;
			}	
		}
		if(anniu_zhuangtai[31]==1)
		{
			if(jianjue[3]==2)
			{
				jianjue[0]=2;	
				jianjue[3]=0;
				zhongdianshu--;	
				dengzhuangtai[31]=0;
			}else if(jianjue[3]==1)
			{	
				jianjue[3]=2;
				dengzhuangtai[31]=1;
				dengzhuangtai[30]=0;
			}	
		}
		if(anniu_zhuangtai[32]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=4;	
				jianjue[4]=1;
				dengzhuangtai[32]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[33]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=4;	
				jianjue[4]=2;	
				dengzhuangtai[33]=1;
				zhongdianshu++;
			}
		}
	}else if(jianjue[0]==4)
	{
		if(anniu_zhuangtai[32]==1)
		{
			if(jianjue[4]==1)
			{
				jianjue[0]=3;	
				jianjue[4]=0;
				dengzhuangtai[32]=0;
				zhongdianshu--;	
			}else if(jianjue[4]!=1)
			{	
				jianjue[4]=1;
				dengzhuangtai[32]=1;
				dengzhuangtai[33]=0;
			}	
		}
		if(anniu_zhuangtai[33]==1)
		{
			if(jianjue[4]==2)
			{
				jianjue[0]=3;	
				jianjue[4]=0;
				zhongdianshu--;	
				dengzhuangtai[33]=0;
			}else if(jianjue[4]==1)
			{	
				jianjue[4]=2;
				dengzhuangtai[33]=1;
				dengzhuangtai[32]=0;
			}	
		}
		if(anniu_zhuangtai[34]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=5;	
				jianjue[5]=1;
				dengzhuangtai[34]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[35]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=5;	
				jianjue[5]=2;	
				dengzhuangtai[35]=1;
				zhongdianshu++;
			}
		}
	}else if(jianjue[0]==5)
	{
		if(anniu_zhuangtai[34]==1)
		{
			if(jianjue[5]==1)
			{
				jianjue[0]=4;	
				jianjue[5]=0;
				dengzhuangtai[34]=0;
				zhongdianshu--;	
			}else if(jianjue[5]==2)
			{	
				jianjue[5]=1;
				dengzhuangtai[34]=1;
				dengzhuangtai[35]=0;
			}	
		}
		if(anniu_zhuangtai[35]==1)
		{
			if(jianjue[5]==2)
			{
				jianjue[0]=4;	
				jianjue[5]=0;
				zhongdianshu--;	
				dengzhuangtai[35]=0;
			}else if(jianjue[5]==1)
			{	
				jianjue[5]=2;
				dengzhuangtai[35]=1;
				dengzhuangtai[34]=0;
			}	
		}
		if(anniu_zhuangtai[36]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=6;	
				jianjue[6]=1;
				dengzhuangtai[36]=1;
				zhongdianshu++;	
			}
		}
		if(anniu_zhuangtai[37]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=6;	
				jianjue[6]=2;	
				dengzhuangtai[37]=1;
				zhongdianshu++;
			}
		}
		if(anniu_zhuangtai[38]==1)
		{
			if(zhongdianshu<zong_max)
			{
				jianjue[0]=6;	
				jianjue[6]=3;	
				dengzhuangtai[38]=1;
				zhongdianshu++;
			}
		}
	}else if(jianjue[0]==6)
	{
		if(anniu_zhuangtai[36]==1)
		{
			if(jianjue[6]==1)
			{
				jianjue[0]=5;	
				jianjue[6]=0;
				dengzhuangtai[36]=0;
				zhongdianshu--;	
			}else if(jianjue[6]!=1)
			{	
				jianjue[6]=1;
				dengzhuangtai[36]=1;
				dengzhuangtai[37]=0;
				dengzhuangtai[38]=0;
			}	
		}
		if(anniu_zhuangtai[37]==1)
		{
			if(jianjue[6]==2)
			{
				jianjue[0]=5;	
				jianjue[6]=0;
				zhongdianshu--;	
				dengzhuangtai[37]=0;
			}else if(jianjue[6]!=2)
			{	
				jianjue[6]=2;
				dengzhuangtai[37]=1;
				dengzhuangtai[36]=0;
				dengzhuangtai[38]=0;
			}	
		}
		if(anniu_zhuangtai[38]==1)
		{
			if(jianjue[6]==3)
			{
				jianjue[0]=5;	
				jianjue[6]=0;
				zhongdianshu--;	
				dengzhuangtai[38]=0;
			}else if(jianjue[6]!=3)
			{	
				jianjue[6]=3;
				dengzhuangtai[38]=1;
				dengzhuangtai[37]=0;
				dengzhuangtai[36]=0;
			}	
		}
	}
	for(fuwei_i=0;fuwei_i<42;fuwei_i++)
	{
		anniu_zhuangtai[fuwei_i]=0; 	
	}
}
void mimapanduan(void)
{
	if((xiongmeng[1]==1)&&(xiongmeng[2]==1)&&(xiongmeng[3]==1)&&(xiongmeng[4]==1)&&(xiongmeng[5]==1)&&(xiongmeng[6]==2)&&(guizha[1]==1)&&(guizha[2]==2)&&(guizha[3]==1)&&(guizha[4]==2))
	{
		for(fuwei_i=0;fuwei_i<42;fuwei_i++)
		{
		 	dengzhuangtai[fuwei_i]=0;
		}
		delay_ms(500);
		for(fuwei_i=0;fuwei_i<42;fuwei_i++)
		{
		 	dengzhuangtai[fuwei_i]=1;
		}
		delay_ms(500);
		for(fuwei_i=0;fuwei_i<42;fuwei_i++)
		{
		 	dengzhuangtai[fuwei_i]=0;
		}
		delay_ms(500);
		for(fuwei_i=0;fuwei_i<42;fuwei_i++)
		{
		 	dengzhuangtai[fuwei_i]=1;
		}
		delay_ms(500);
		for(fuwei_i=0;fuwei_i<42;fuwei_i++)
		{
		 	dengzhuangtai[fuwei_i]=0;
		}
		delay_ms(500);
		for(fuwei_i=0;fuwei_i<42;fuwei_i++)
		{
		 	dengzhuangtai[fuwei_i]=1;
		}
		delay_ms(500);
	}
}